### ISSUE TITLE
Apropiación de generalidades

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/core_api#11]
Asimilar el funcionamiento general del sistema a trabajar, así como de su flujo y acciones necesarias por implementar, de acuerdo a las siguientes actividades:
 
- [x] Revisión e instalación de repositorios (Crud, Mid y Cliente).
- [x] Revisión de documentación. ([CORE](https://drive.google.com/drive/folders/1p3DWqsG7g-rSCLZPqdnj8hfQpOIc4kNe?usp=sharing))
- [x] Análisis de requerimientos.

**Criterios de aceptación**

1. Registrar el estado actual en el que se recibe el sistema para la funcionalidad específica a implementar (Elaboración propia).
2. Registrar inquietudes respecto a los requerimientos analizados.

**Comment by FelipeVel** [comment]
[Estado actual de funcionalidad QR](https://drive.google.com/file/d/1qP2btt9-OJ56f1JoyFPwAeqHTm-d1uwM/view?usp=sharing)
