### ISSUE TITLE
Apropiación de generalidades - Modulo de notificaciones.

### ISSUE THREAD

**Issue by a52290451** [udistrital/core_api#12]
Analizar el requerimiento solicitado, así como sus flujos y acciones necesarias por implementar, de acuerdo a las siguientes actividades:

- [x] Revisión e instalación de repositorios (opcional).
- [x] Revisión de documentación relacionada.
- [x] Análisis de requerimientos.

**Material de apoyo**

- [Issues relacionados](https://github.com/udistrital/notificacion_api/issues?q=is%3Aissue+is%3Aclosed).
- [notificacion_documentacion](https://github.com/udistrital/notificacion_documentacion).
- [notificacion_crud](https://github.com/udistrital/notificaciones_crud).
- [Sistema de notificaciones](https://docs.google.com/document/d/1Z_1sb4f0_gEPXS_5AHoTGnKgpLfjR6-_98F0XRnBVVA/edit#heading=h.37o5xb65948r).
- [Investigación reciente](https://docs.google.com/document/d/1hg7ew3O6GMUtrA8y6bNRvWgsmNeiW4k5roDcbIbwk9A/edit).

**Comment by FelipeVel** [comment]
Se adjunta la [propuesta de trabajo](https://docs.google.com/document/d/1oGwYyat0GP5VrqlJ-e-PVt3l9KvcL_fmsBB_EZLebJ8/edit?usp=sharing)

**Comment by a52290451** [comment]
Se adjunta [Sprint Planning](https://docs.google.com/document/d/181CWibKKch4dbHgetMN16D22VQHGeLsz/edit?usp=sharing&ouid=104124925692794756698&rtpof=true&sd=true) asociado a la propuesta de trabajo.
