### ISSUE TITLE
Revisión de documentación existente

### ISSUE THREAD

**Issue by a52290451** [udistrital/core_api#15]
Se requiere realizar la revisión de documentación existente asociada a JANO, incluyendo la resolución relacionada con el ultimo concurso docente que se llevó a cabo. Esto con el fin de identificar los elementos y flujos que conforman el sistema JANO.

**Criterios de aceptación**

- [x] Adjuntar última resolución asociada al concurso docente.
- [x] Documento en el cual se especifiquen los elementos clave que componen el concurso y que deben estar contemplados en el sistema JANO.

**Comment by criss201x** [comment]
Se realiza un análisis de las resoluciones y acuerdos relacionados al primer concurso publico y abierto de méritos para la contratación de planta docente en la universidad, inicialmente se adjuntan dichas resoluciones como soporte para corroborar o re definir reglas de negocio en el aplicativo JANO el cual esta definido para llevar a cabo dicho proceso.

- [Resolución 93 del 20 de junio de 2019](https://drive.google.com/file/d/1LQEnoDesa0TZ1k_BTVRKV4M4up6WYNck/view?usp=sharing):  donde se corrigen ambigüedades en la resolución 081, se re definen recursos de reposición y apelación dentro y fuera del concurso, se aclaran roles para algunos procesos, entre otras particularidades de la anterior resolución ... 
- [Resolución 081 del 31 de mayo de 2019](https://drive.google.com/file/d/1RQP1nORWI2ZieMVvW_p6m1mEGtLZ3ycN/view?usp=sharing): Es la resolución oficial del primer concurso publico y abierto de méritos, donde se definen requisitos de los aspirantes y reglas generales del concurso, esta toma como referencia el acuerdo 005 del 2007 para la definición del reglamento del concurso.
- [Acuerdo 005 del 5 de octubre del 2007](https://drive.google.com/file/d/1qAXFCX-ehJW6AFap-ZNnxhYVZfOC4Uf4/view?usp=sharing): Define todas las reglas y lineamientos correspondientes para todos los concursos públicos de méritos para la contratación de planta docente en la universidad.

**NOTA:** Se debe comprobar gran parte de las reglas del concurso en el aplicativo JANO (pendiente).

**Comment by criss201x** [comment]
Se adjunta documento de análisis con el fin de consolidar reglas de negocio (resoluciones), antecedentes del proyecto JANO, backlog Tuleap, artefactos, entre otros ... 

- [Documento de análisis](https://docs.google.com/document/d/1MD5cyjM0OYwmotP7m_lec8Db9B7PA4_WQFVD0pL5QXY/edit?usp=sharing)

**Comment by a52290451** [comment]
Se valida análisis realizado en JANO en cuanto a su documentación.
