### ISSUE TITLE
Instalación y configuración de entorno de desarrollo local para JANO

### ISSUE THREAD

**Issue by a52290451** [udistrital/core_api#16]
Realizar la instalación, configuración y su respectiva documentación del entorno de desarrollo local para frameworks antiguos de PHP (SARA) utilizando, en este caso, el sistema JANO.

**Criterios de aceptación**

- [x] Instalación y configuración del entorno de desarrollo.

- [x] Manual de configuración del entorno de desarrollo.

**Comment by criss201x** [comment]
La configuración del sistema legado Jano es similar a la de Agora, varia en el momento de configurar la clase encriptador  y el archivo config.inc.php, estas observaciones se colocaron en el manual general de configuración SARA, tener en cuenta que para dicha configuración se requiere tener una instancia de base de datos del sistema en local este proceso se debe realizar por medio del equipo de dba.  

- [Manual de ambiente de configuracion de ambiente de desarrollo Sara actualizado](https://docs.google.com/document/d/1XELFDa5i7mvdsaa7AN9JX5wEPMEX6Vum/edit?usp=sharing&ouid=110288693142592643207&rtpof=true&sd=true)

**Comment by criss201x** [comment]
Se actualiza manual de configuración de ambiente de desarrollo Sara de acuerdo a nuevo formato establecido por la oficina, se hacen algunas modificaciones en el manual con el fin de que este repose en el sistema base de conocimiento oas

- [Manual de configuración de ambiente de desarrollo Sara versión 2 ](https://docs.google.com/document/d/1Vk-970-Kj1RUxRE04sfpHnPW-dQ_eViI/edit?usp=sharing&ouid=110288693142592643207&rtpof=true&sd=true)
