### ISSUE TITLE
Diagnosticar el sistema (pruebas funcionales)

### ISSUE THREAD

**Issue by a52290451** [udistrital/core_api#17]
Se requiere realizar el diagnostico del sistema JANO mediante la ejecución de pruebas funcionales, para identificar el estado en que se encuentra y los problemas a solucionar.

**Criterios de aceptación**

- [x] Documentación de pruebas funcionales realizadas.
- [x] Tomando en consideración la [Revisión de documentación](https://github.com/udistrital/core_api/issues/15) realizada, identificar las partes faltantes en el sistema.

Nota: utilizar el [formato](https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit#gid=481118634) de pruebas funcionales, como base para la documentación de estas pruebas

**Comment by criss201x** [comment]
Se inician pruebas funcionales tomando como criterios de diagnostico los procesos del siguiente diagrama
![Captura de pantalla de 2021-12-06 15-25-21](https://user-images.githubusercontent.com/57843585/144922452-528a2422-849d-4dbd-89cc-a784f7439974.png)

**Comment by criss201x** [comment]
Se realizaron pruebas funcionales en en el sistema concurso de méritos Jano, donde se evidencio que algunas funcionalidades de dicho sistema presentan fallos, todas las pruebas del diagnostico junto con sus respectivos hallazgos se registraron en el siguiente formato.  

- [Documento de pruebas funcionales JANO 2021](https://docs.google.com/spreadsheets/d/1VVC5wNjx-2NkxUpSAjPcaFAJMiBuHWR8/edit?usp=sharing&ouid=110288693142592643207&rtpof=true&sd=true)
