### ISSUE TITLE
Estabilizar el sistema.

### ISSUE THREAD

**Issue by a52290451** [udistrital/core_api#18]
De acuerdo al proceso de [diagnostico del sistema](https://github.com/udistrital/core_api/issues/17) realizado, implementar acciones que permitan estabilizar el sistema.

- Arreglo del módulo de asignación de jurado.
- Arreglo del módulo de asignación de evaluadores.

**Criterios de aceptación**

- [x] Commit en ambiente de pruebas con los cambios realizados,

**Comment by criss201x** [comment]
El sistema actualmente se encuentra estable, el modulo de asignación de jurados y evaluadores ademas de la asignación de sus respectivos aspirantes presentan ambigüedades, se debe aclarar que cualquier jurado o evaluador debe ser un usuario registrado y este debe tener el rol adecuado, los roles únicamente los da el administrador del sistema en el modulo de gestión de usuarios 
 
- se valida la asignación de roles a un usuario de pruebas
![Captura de pantalla de 2022-01-21 15-59-42](https://user-images.githubusercontent.com/57843585/150599389-dbd3c584-cdea-4abf-a107-8b046fc13d55.png)

- Cualquier usuario con el rol de jurado o evaluador solo puede evaluar aspirantes cuando el usuario administrador del concurso le ha asignado aspirantes por medio del modulo de seguimiento concurso sin embargo en la fase de evaluación de requisitos cualquier usuario con el rol docencia puede evaluar un aspirante sin haber sido asignado por medio del administrador.
![Captura de pantalla de 2022-01-20 17-06-46](https://user-images.githubusercontent.com/57843585/150598414-cb155d3f-29dc-40a2-b7d5-8ccc09cbc027.png) 
![Captura de pantalla de 2022-01-21 16-20-17](https://user-images.githubusercontent.com/57843585/150601639-afd2c67b-e3bf-4e48-aed6-fd99b6b5e5cd.png)

- En el modulo de seguimiento concurso en el apartado de asignar evaluadores y jurados a los diferentes aspirantes, se puede observar un formulario y después una tabla, este ultimo componente esta sobrando en el front, ya que al dar click en el boton 'asignar aspirantes a jurado' este redirecciona a otro formulario donde se hace el respectivo proceso   
![Captura de pantalla de 2022-01-21 17-03-35](https://user-images.githubusercontent.com/57843585/150608235-d7212c1a-c497-4e5e-871b-15bac8cfba8a.png)
![Captura de pantalla de 2022-01-21 17-27-02](https://user-images.githubusercontent.com/57843585/150608456-e6ad7f94-5809-4cf7-9d9a-ce44ad2575d6.png)

- A cada jurado se le asignan evaluaciones de acuerdo su rol, es decir que cada criterio de evaluación del concurso tiene una relación con el tipo de rol del usuario.
